### ISSUE TITLE
DjangoModelFactory.build hits the database

### ISSUE THREAD

**Issue by hannesstruss** [rbarrois/factory_boy#111]
given this constellation:

    class MyModel(models.Model):
        name = models.CharField(max_length=100)

    class ModelFactory(DjangoModelFactory):
        FACTORY_FOR = MyModel
    
        name = 'John Doe'

    class MyTestCase(TestCase):
        def test_factory(self):
            ModelFactory.build()

The test case will hit the database when generating an ID for the model (Stacktrace when using py.test that detects database usage in tests: https://gist.github.com/hannesstruss/f60e038daa588318ea57 )

I would expect .build() to not touch the database at all, but to create in-memory/test-local objects only. As far as I remember that was also how it worked before all Django-specific code was moved to DjangoModelFactory.

If this is expected, sorry for missing the memo :) What would be the best practice then to share code between a factory that does and one that doesn't save the model?

I tested in 2.2.1/Django 1.6.

**Comment by rbarrois** [comment]
This issue has been fixed in 13d310f, and will be part of the 2.5.0 release.
