### ISSUE TITLE
Metaclass for BaseFactory too agressive in removing attrs

### ISSUE THREAD

**Issue by mjtamlyn** [rbarrois/factory_boy#135]
I would like to extend a Factory subclass to add a custom "build" style classmethod. I've got a model structure which (simplified) looks like:
```A <- B <- D -> C -> A```
The fks through B and C should always point at the same A for a given D. As this requires about three lines of typing (there's more than one model at B and C), the idea was to build:
```
class Dfactory(factory.Factory):
    @classmethod
    def for_a(cls, a, **kwargs):
        kwargs.update(b__a=a, c__a=a)
        cls(**kwargs)
```

Unfortunately, the Metaclass on BaseFactory throws away the classmethod, without raising any errors. This is not expected python behaviour.

**Comment by rbarrois** [comment]
Hi,

I think I might have fixed that test somewhere in the last few releases; feel free to reopen it if it still hurts you :)
