### ISSUE TITLE
Factories doesn't seem to work if a session hasn't been used yet.

### ISSUE THREAD

**Issue by jpanganiban** [rbarrois/factory_boy#153]
I'm working with SQLAlchemy (with a scoped_session). Here's what I'm getting:

```
class TestCase(unittest.TestCase):

    def setUp(self):
        self.obj = ObjectFactory()
        print self.obj.id  # None

    def test_scenario(self):
        print self.obj.id  # None; Weird.
        session.query(Object).first()
        print ObjectFactory().id  # 1; Weird.
```

EDIT:
`setUp` doesn't seem to be the causing issue. It seems that `_setup_next_sequency()` doesn't get any primary keys to use if the session hasn't been used yet.

**Comment by rbarrois** [comment]
This issue has been fixed in 13d310f, and will be part of the 2.5.0 release.
