### ISSUE TITLE
better docs: Create Master-Detail instances without touching DB

### ISSUE THREAD

**Issue by guettli** [rbarrois/factory_boy#154]
I want to create a "master" object which is referenced by N "detail" objects.

Please explain in the docs how to create this with "build" strategy (without touching the DB).

We use the django ORM.

There is already a good example in the docs for the "create" strategy: http://factoryboy.readthedocs.org/en/latest/recipes.html#simple-manytomany

The same for "build" strategy would be very nice.

**Comment by jeffwidman** [comment]
Closing, since this is no longer an active issue. 

@guettli feel free to submit a PR adding a note about this to the docs.

**Comment by guettli** [comment]
Yes, solved. It is documented now: In this public accessible issue :-)
