### ISSUE TITLE
Multi-db no longer supported.

### ISSUE THREAD

**Issue by ashchristopher** [rbarrois/factory_boy#170]
In `DjangoModelFactory`, the factory will eventually make a call to `_setup_next_sequence` regardless of whether we are `build`ing or `create`ing. This means the strategy of building an instance, then settings it's destination via `save(user='other_db')` is no longer valid.

When using `factory.BUILD_STRATEGY`, it should not be hitting the database at all.

I can mitigate this issue by overriding the `_setup_next_sequence()` method.

```
@classmethod
def _setup_next_sequence(cls):
    return 1
```

**Comment by rbarrois** [comment]
This issue has been fixed in 13d310f, and will be part of the 2.5.0 release.
