### ISSUE TITLE
How to specify the database for Factory Boy?

### ISSUE THREAD

**Issue by houmie** [rbarrois/factory_boy#171]
http://stackoverflow.com/questions/26550262/how-to-specify-the-database-for-factory-boy

Many Thanks,
Houman

**Comment by TBeijen** [comment]
I'm running into the same issue, my setup:

```python
if IS_UNITTEST:
    DATABASES['default']['ENGINE'] = 'django.db.backends.sqlite3'
    DATABASES['default']['TEST_MIRROR'] = 'master'
    DATABASES['default']['TEST_DEPENDENCIES'] = ['master']
    DATABASES['master']['ENGINE'] = 'django.db.backends.sqlite3'
    DATABASES['master']['TEST_DEPENDENCIES'] = []
```
Our app mainly reads and just recently we needed to introduce a separate master DB. Of course I could make the write DB 'default' and change the former default into slave but I feel that should not be motivated by testsuite issues. 

I've changed the _get_manager() method to actually use the django db routing and that seems to work nicely:

```python
import factory
from django.db.utils import ConnectionRouter

class ModelFactory(factory.DjangoModelFactory):

    @classmethod
    def _get_manager(cls, model_class):
        manager = super(ModelFactory, cls)._get_manager(model_class)
        router = ConnectionRouter()
        db = router.db_for_write(model_class)
        return manager.using(db)

class ArticleFactory(ModelFactory):
    FACTORY_FOR = Article
```

Of course I can issue a pull request.

**Comment by rbarrois** [comment]
Hi @TBeijen 

Thanks for the use case, which I hadn't identified (the app just reads, but tests need to write to another database).
Before writing a pull request, could you describe the behavior you'd like to see?

I was thinking along the lines of:

```python
class ArticleFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = models.Article
        database = 'master'
```

**Comment by mmautner** [comment]
Is there a reasonable way to monkeypatch the database name at run-time?

**Comment by TBeijen** [comment]
Apparently I totally forgot to get back to this issue.

As to the monkeypatch question. My first question would be: Why? Do you really need a single factory to use different databases? If possible just make it part of your manager.

If varying per test is needed, I suppose the ``_get_manager()`` class-method might be a good starting point.
Something along the lines of a context manager that takes a factory class and db name as argument and replaces the ``get_manager()`` method to return a manager that uses the desired db.

You'd end up with something like this:

```
with use_db(MyFactory, 'replica'):
    MyFactory.create(foo='bar')
```

**Comment by jeffwidman** [comment]
There's also a StackOverflow tag for FB.

**Comment by eLRuLL** [comment]
the Context Manager idea looks promising, @TBeijen I would really appreciate if you could share a working example of that. I tried to implement one by myself but got stuck on overriding a @classmethod and how to pass the database name to `_get_manager`  inside the `__enter__` method (this was my first attempt to create a Context Manager). 

I also created a [SO question](https://stackoverflow.com/questions/48753155/django-how-to-specify-database-dynamically-for-factory-boy) about it.

Kind Regards.
