### ISSUE TITLE
Document _prepare function

### ISSUE THREAD

**Issue by rightaway** [rbarrois/factory_boy#179]
I saw some code posted somewhere that used a _prepare function. I tried it and it worked and I found it useful. Would be good to have it in the documentation, as well as how it differs from @factory.post_generation (not clear on this). An example like:

```
    @classmethod
    def _prepare(cls, create, **kwargs):
        object = super(MyParentFactory, cls)._prepare(create, **kwargs)
        object.myfield = hash_function(object.myfield)
        return object
```

**Comment by rbarrois** [comment]
Hi,

I have since then documented the ``_adjust_kwargs`` function: http://factoryboy.readthedocs.org/en/latest/reference.html#factory.Factory._adjust_kwargs

With this, your example would look like this:

```python
@classmethod
def _adjust_kwargs(cls, **kwargs):
    kwargs = super(MyFactory, cls)._adjust_kwargs(**kwargs)
    kwargs['my_field'] = hash_function(kwargs['my_field']
    return kwargs
```
