### ISSUE TITLE
UUID as PK does not work with _setup_next_sequence

### ISSUE THREAD

**Issue by joscarsson** [rbarrois/factory_boy#181]
I have a model where the PK is a UUID (`sqlalchemy.dialects.postgres.UUID`), as below.

```python
class Item(DatabaseModel):
    __tablename__ = 'items'

    id = Column(UUID, primary_key=True, default=lambda: uuid4().hex)
```

When using factory_boy with this model, I get the error below when factory_boy tries to execute `_setup_next_sequence()`.

```
ProgrammingError: (ProgrammingError) function max(uuid) does not exist
SELECT max(items.id) AS max_1 FROM items
```

`_setup_next_sequence()` tries to get the next ID to use for the PK, and assumes the PK is an int.

```python
    @classmethod
    def _setup_next_sequence(cls, *args, **kwargs):
        """Compute the next available PK, based on the 'pk' database field."""
        session = cls.FACTORY_SESSION
        model = cls.FACTORY_FOR
        pk = getattr(model, model.__mapper__.primary_key[0].name)
        max_pk = session.query(max(pk)).one()[0]
        if isinstance(max_pk, int):
            return max_pk + 1 if max_pk else 1
        else:
            return 1
```

The workaround I'm currently using is:

```python
class UUIDAwareSQLAlchemyModelFactory(SQLAlchemyModelFactory):
    @classmethod
    def _setup_next_sequence(cls, *args, **kwargs):
        model = cls.FACTORY_FOR
        pk_type = model.__mapper__.primary_key[0].type

        if isinstance(pk_type, UUID):
            return 1

        return super(UUIDAwareSQLAlchemyModelFactory, cls)._setup_next_sequence(*args, **kwargs)
```

As the PKs cannot be generated by postgres anyway (see the `default=` kwarg for the `Column` in the model above), I don't need sequence support for them.

Could something like this be added to factory_boy's `SQLAlchemyModelFactory` so the workaround isn't needed?

**Comment by rbarrois** [comment]
Hi,

This was a nasty non-feature, that has been removed in 13d310f.
It should be fixed in master, which will be released "soon™" :)
