### ISSUE TITLE
Seeds for factories to reproduce

### ISSUE THREAD

**Issue by mihaicc** [rbarrois/factory_boy#185]
### Need:
```Gherkin
Given I use factories in my tests
And those factories generate random data for some fields
When I run a test which fails depending on the random generated data
Then I need to reproduce the test consistently to fix the problem
```

### Deliverable:
A way of settings a global seed for the randoms to become fixed and being able to reproduce the error in the test constantly.

### Solution:
 - [ ] One idea would to set the seed on random at first factory import
 - [ ] Print the seed so it appears in the log of the broken test
 - [ ] allow the seed to be set somewhere for next test run.

### Notes:
 - Seed might not be enough, see difference between seed and getstate
 - This issue might not make sense if other libs except random are used. Or maybe the the principle should be abstracted to still apply.

**Comment by rbarrois** [comment]
Hi @mihaicc !

I've just added commit 97a8890 to enable this; ``factory.fuzzy`` now uses a separated random generator, with helpers to get/set its state.

How that state is used in one's test setup isn't managed by factory_boy, but this enables to print the current "state" before tests.

**Comment by warvariuc** [comment]
@Brodan probably this https://factoryboy.readthedocs.io/en/stable/_modules/factory/random.html
