### ISSUE TITLE
importing MongoEngineFactory is weird

### ISSUE THREAD

**Issue by dustinfarris** [rbarrois/factory_boy#186]
Following the style of other factories, I have:

```python
import factory


class MyModelFactory(factory.mongoengine.MongoEngineFactory):
    
    class Meta:
        model = 'myapp.MyModel'
```

but this throws an import error:

```
AttributeError: 'module' object has no attribute 'mongoengine'
```

however, this works:

```python
from factory.mongoengine import MongoEngineFactory


class MyModelFactory(MongoEngineFactory):
    
    class Meta:
        model = 'myapp.MyModel'
```

**Comment by rbarrois** [comment]
Yes indeed.

But AFAIK, declaring ``factory.mongoengine`` in ``factory/__init__.py`` would require ``mongoengine`` to be installed for all users of factory_boy.

This would be quite painful for most users, so I'll avoid it; however, feel free to reopen the issue if you know of simple ways of enabling this "lazy loading"!

**Comment by dustinfarris** [comment]
I don't quite follow.  `factory.mongoengine.MongoEngineFactory` doesn't seem to actually import mongoengine itself in any way.  The tests do, but they are already conditionally run depending on whether mongoengine is actually available or not.  Or am I missing something?

**Comment by rbarrois** [comment]
That's indeed a good point.

I'll look into it.
