### ISSUE TITLE
Sequence changed from starting at 1 to starting at 0

### ISSUE THREAD

**Issue by tysonzero** [rbarrois/factory_boy#190]
I did not see it in the patch notes, was it something to do with the "auto-magical sequence setup" thing that was mentioned.

I am currently switching everything over to compensate for this change, as currently most of my tests fail (I use Sequence on pretty much all my factories), but before I push all my changes I wanted to make sure this was an intentional change.

**Comment by rbarrois** [comment]
Yes, this was indeed intentional (and a side effect of no longer looking at ``max(pk) + 1``).

Sorry for the breakage however; 2.4.1 is still available on PyPI if you need.

**Comment by tysonzero** [comment]
I'll just stick with 1.5, I already did the work switching it over, just didn't want to push until I knew for sure. Thanks for the info.
