### ISSUE TITLE
Make previous versions of factory_boy available on PyPI

### ISSUE THREAD

**Issue by kristaps** [rbarrois/factory_boy#191]
2.5.0 was released yesterday and it breaks our builds. We would like to pin the factory_boy requirement to an earlier version, until we can sort out why the builds are failing and update our factory_boy usage. This is currently not possible as only the latest version of factory_boy is available on PyPI and we create a clean virtualenv for each build.

**Comment by daGrevis** [comment]
+1

**Comment by rbarrois** [comment]
Done.

I've also added upgrade instructions to the changelog (http://factoryboy.readthedocs.org/en/latest/changelog.html#upgrading).
