### ISSUE TITLE
Django Factory gets the wrong manager for model on 2.5.0

### ISSUE THREAD

**Issue by rubendura** [rbarrois/factory_boy#192]
Using factory_boy 2.5.0 break my build. I have a model using a custom manager for object creation but factory_boy is somehow ignoring it and using Django's default manager. When creating an object using my factory I expected I could pass extra arguments that my custom manager accepts. The documentation statest that 
> create() uses Model.objects.create()

but that doesn't seem to be true in 2.5.0.

I tried setting my model meta using import model syntax

    from models import Model
    class Meta:
        model = Model

and 'app.Model' syntax

    class Meta:
        model = 'app.Model'

None of them work. factory_boy 2.4.1 works fine, but I can't figure out what changed between those versions that broke it.

**Comment by rbarrois** [comment]
Hi,

Could you provide an example of how you declare your custom manager? I think the change comes from commit 636ca46951d710a4b9d9fd61ec1da02294806d3d.

**Comment by rubendura** [comment]
You can see the issue happening on the following commit.

https://github.com/rubendura/factory_boy/commit/417c16926397dc7e281bd7bfd94d434c57228f7a

That test passes under commit 25bd44c30007d5babecefed651827431569ee1ee "Fix support for Django 1.7."

Don't know if I should do a pull request for this as it only adds a failing test and no solution to it.
