### ISSUE TITLE
Can't pass None to a JSON column in create() even if it's none_as_null

### ISSUE THREAD

**Issue by zdexter** [rbarrois/factory_boy#196]
Passing None to a postgres JSON column (`sqlalchemy.dialects.postgresql.JSON` with `default={}` and `none_as_null=True` currently has a bug.

```
model_instance = SomeFactory.create(json_column_name=None)
self.assertEqual(model_instance.json_column_name, None) # False
self.assertEqual(model_instance.json_column_name, {}) # True
```

factory-boy==2.4.1
SQLAlchemy==0.9.9

**Comment by rbarrois** [comment]
This is unlikely to be a factory_boy issue: factory_boy will simply call:

```python
obj = MyModel(json_column_name=None)
session.add(obj)
```

Could you try the above snippet (i.e without using factory_boy) to check if you reproduce this behavior?

**Comment by jeffwidman** [comment]
Postgres JSON support has been improved a good deal in SQLAlchemy > 0.9.9, plus using the JSON operators is often a bit confusing. So I'm going to close this, as I suspect it's either a user or SQLAlchemy issue. If you can replicate with the latest version of SQLAlchemy, and can provide a short test script that reproduces the error then I'll happily re-open.
