### ISSUE TITLE
Support for Peewee ORM?

### ISSUE THREAD

**Issue by coleifer** [rbarrois/factory_boy#200]
Hi @rbarrois! I was curious if you had any plans to add support for [peewee ORM](https://github.com/coleifer/peewee)? I believe the implementation would be quite short, as Peewee has a very simple API for creating model instances. If you do not plan on implementing it yourself, would you accept a pull-request?

Thanks again for your work!

**Comment by rbarrois** [comment]
Hi @coleifer ,

I have currently zero knowledge of peewee, so adding support would be kinda difficult - and I wouldn't be able to maintain it.

I haven't been able to design a simple and manageable way to add robust, maintained third-party compatibility in factory_boy — this would require following closely the evolution of each third-party lib.

If you're interested in contributing peewee support in factory_boy, what organization would you expect/need?

**Comment by coleifer** [comment]
After searching around, it looks like another user has actually implemented this feature already:

https://github.com/cam-stitt/factory_boy-peewee

So I think it's safe to close. Thanks!

**Comment by Seluj78** [comment]
I think it'd be interesting to re-open this issue as the problem still exists today. The repository @coleifer mentioned isn't active anymore.

I currently use this code to use `factory_boy` with `peewee`:

```py
import peewee
from factory import base


class PeeweeOptions(base.FactoryOptions):
    def _build_default_options(self):
        return super(PeeweeOptions, self)._build_default_options() + [
            base.OptionDefault("database", None, inherit=True),
        ]


class PeeweeModelFactory(base.Factory):
    """Factory for peewee models."""

    _options_class = PeeweeOptions

    class Meta:
        abstract = True

    @classmethod
    def _setup_next_sequence(cls, *args, **kwargs):
        """Compute the next available PK, based on the 'pk' database field."""
        model = cls._meta.model
        pk = getattr(model, model._meta.primary_key.name)
        max_pk = model.select(peewee.fn.Max(pk).alias("maxpk")).limit(1).order_by().execute()
        max_pk = [mp.maxpk for mp in max_pk][0]
        if isinstance(max_pk, int):
            return max_pk + 1 if max_pk else 1
        else:
            return 1

    @classmethod
    def _create(cls, target_class, *args, **kwargs):
        """Create an instance of the model, and save it to the database."""
        obj = target_class.create(**kwargs)
        return obj
```
