### ISSUE TITLE
"FactoryError: Cannot generate instances of abstract factory" with django-factory_boy

### ISSUE THREAD

**Issue by blueyed** [rbarrois/factory_boy#205]
I am seeing a FactoryError when using django-factory_boy (Git master, the version on PyPI is not compatible with factory_boy!).

Django 1.8.

This might be related to #201.

    E           factory.base.FactoryError: Cannot generate instances of abstract factory UserFactory; Ensure UserFactory.Meta.model is set and UserFactory.Meta.abstract is either not set or False.
        @pytest.fixture
        def user():
            from django_factory_boy import auth as auth_factories
            import ipdb; ipdb.set_trace()
    >       return auth_factories.UserFactory()

    auth_factories = <module 'django_factory_boy.auth' from '…/django-factory_boy/django_factory_boy/auth.py'>
    ipdb       = <module 'ipdb' from '…/pyenv/project3/lib/python3.4/site-packages/ipdb/__init__.py'>

    project/conftest.py:117:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    …/pyenv/project3/lib/python3.4/site-packages/factory/base.py:81: in __call__
        return cls.create(**kwargs)
    …/pyenv/project3/lib/python3.4/site-packages/factory/base.py:559: in create
        return cls._generate(True, attrs)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    cls = <class 'django_factory_boy.auth.UserFactory'>, create = True
    attrs = {'FACTORY_FOR': <class 'django.contrib.auth.models.User'>, 'date_joined': datetime.datetime(1999, 1, 1, 0, 0), 'email': 'email0@example.com', 'first_name': 'first_name0', ...}

        @classmethod
        def _generate(cls, create, attrs):
            """generate the object.

                Args:
                    create (bool): whether to 'build' or 'create' the object
                    attrs (dict): attributes to use for generating the object
                """
            if cls._meta.abstract:
                raise FactoryError(
                    "Cannot generate instances of abstract factory %(f)s; "
                    "Ensure %(f)s.Meta.model is set and %(f)s.Meta.abstract "
    >               "is either not set or False." % dict(f=cls.__name__))
    E           factory.base.FactoryError: Cannot generate instances of abstract factory UserFactory; Ensure UserFactory.Meta.model is set and UserFactory.Meta.abstract is either not set or False.

    attrs      = {'FACTORY_FOR': <class 'django.contrib.auth.models.User'>, 'date_joined': datetime.datetime(1999, 1, 1, 0, 0), 'email': 'email0@example.com', 'first_name': 'first_name0', ...}
    cls        = <class 'django_factory_boy.auth.UserFactory'>
    create     = True

    …/pyenv/project3/lib/python3.4/site-packages/factory/base.py:475: FactoryError

**Comment by schinckel** [comment]
My understanding is that this is related to https://github.com/rbarrois/factory_boy/commit/69894fce7977ea55f8cc3ad141840bab49330859

I believe we need to change the shape of our factories now?

**Comment by schinckel** [comment]
Is there any chance we can get the ability to use FACTORY_FOR restored, but deprecated, with LOUD SHOUTY WARNINGS to fix? Or perhaps even just a suggestion on how to fix it?

**Comment by rbarrois** [comment]
Hi,

I'll try to get a release of django_factory-boy out today.
In the meantime, you can use factory_boy-2.4.

**Comment by schinckel** [comment]
No biggie: I was able to just change the factory definitions. It would have just been even more awesome to be told more about why my factories were abstract. Clearly I didn't read the docs enough before upgrading... ;)

**Comment by blueyed** [comment]
The related PR for django_factory-boy seems to be: https://github.com/rbarrois/django-factory_boy/pull/2

**Comment by jeffwidman** [comment]
Closing, as I think from reading the comment thread that this is now solved. If it's still an issue, please comment and we'll re-open.
