### ISSUE TITLE
Factory attribute with reserved name (attributes).

### ISSUE THREAD

**Issue by kevinastone** [rbarrois/factory_boy#206]
Have a model with a field name `attributes` that I'm unable to create due to it being a reserved method on the factory:

```
class TestFactory(factory_boy.Factory):
    attributes = 'something'
```

Results in:
```
>>> TestFactory.create()
*** TypeError: 'str' object is not callable
```

Is there a way to alias the attribute names to avoid this collision?

**Comment by rbarrois** [comment]
Hi,

This should be fixed in the next release (hopefully within a couple of weeks), with ``Meta.rename``.

In the meantime, you can also use the ``_adjust_kwargs`` method:

```python
class TestFactory(factory.Factory):
    attrs = 'something'

    @classmethod
    def _adjust_kwargs(cls, kwargs):
        kwargs['attributes'] = kwargs.pop('attrs')
        return kwargs
```

**Comment by ibushong** [comment]
Minor typo in your last post, `kwargs` --> `**kwargs`. Thanks for this though, solved my issue too.
