### ISSUE TITLE
ForeignKey doesn't work when custom db_name is set, Django ORM

### ISSUE THREAD

**Issue by don-mums** [rbarrois/factory_boy#208]
What I use:

 * Python 3.4.3
 * Django 1.7.7
 * factory_boy 2.5.2

When I call `create()` on factory_boy class it always sets foreign keys correctly on `SubFactory` fields. But when I define custom `db_name` it doesn't work. Factory_boy simply doesn't set `ForeignKey` or `OneToOneField` when I use `SubFactory`. I tried to Google for workaround but I couldn't find anything.

Table column definition:
`check_ptr = models.ForeignKey('Check', db_column='check_id')`

Factory class sample:

    class CheckFactory(DjangoModelFactory):
        order = factory.SubFactory(CheckOrderFactory)

        class Meta:
            model = Check

`check_ptr` is always set to None/null.

This text is identical to question on stackoverflow: https://stackoverflow.com/questions/30302020/factory-boy-custom-db-name-in-foreignkey-django-orm

**Comment by rbarrois** [comment]
Hi,

I need more info to handle this; here are the same details I put on your stackoverflow question:

Your example seems strange to me: if your ``CheckOrder`` has a ``ForeignKey`` to ``Check``, the ``SubFactory`` should be defined on ``CheckOrderFactory``, not on ``CheckFactory``.

In other words, this should work:

```python
class CheckFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Check

class CheckOrderFactory(factory.django.DjangoModelFactory):
    check_ptr = factory.SubFactory(CheckFactory)

    class Meta:
        model = CheckOrder
```

Beyond this, you mention ``db_name`` but don't use it anywhere in your example; could you explain what you meant?

**Comment by rbarrois** [comment]
Hi,

I'm doing some cleanup on old issues (before setting up a mailing-list, which should be a better fit for those questions); feel free to reopen the issue if it's still hurting you!
