### ISSUE TITLE
Common recipe for reverse dependencies doesn't work

### ISSUE THREAD

**Issue by pedrospdc** [rbarrois/factory_boy#214]
The common recipe for a RelatedFactory (on http://factoryboy.readthedocs.org/en/latest/recipes.html) shows as this:

```python
# models.py
class User(models.Model):
    pass

class UserLog(models.Model):
    user = models.ForeignKey(User)
    action = models.CharField()


# factories.py
class UserFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = models.User

    log = factory.RelatedFactory(UserLogFactory, 'user', action=models.UserLog.ACTION_CREATE)
```

At least with Django 1.8.2 these actions are nowhere to be found, raising an attribute error.

**Comment by pedrospdc** [comment]
Oh god I think I have brain damage.

Nevermind. I got everything wrong :P

**Comment by mzaanen** [comment]
Please, could you share your solution... I am stuck at the same point. From your answer it seems to be something obvious.

**Comment by pavan-blackbuck** [comment]
I have the same issue. Can you please share the solution?

**Comment by rbarrois** [comment]
@pavan-blackbuck If I understand correctly, the issue was that the example code expected the user to have defined some ``ACTION_CREATE`` on the custom ``UserLog`` model; obviously, this would fail if you don't define such fields on your own models.

**Comment by pedrospdc** [comment]
Sorry guys it's been two years. Wish I had posted it down back then...

**Comment by pavan-blackbuck** [comment]
@rbarrois Thank you. Got this resolved.
