### ISSUE TITLE
Generic Foreign Keys and Rails-like polymorphic associations

### ISSUE THREAD

**Issue by Amnesthesia** [rbarrois/factory_boy#215]
I can't seem to figure out how to implement a GenericForeignKey with FactoryBoy. I have a model `Comment` and a model `Post`, but `Comment` can be attached to mostly anything. In Python (django), these look like:

```python
class Comment(models.Model):
    """Comment for any other object."""

    #: Message for the Comment
    message = models.TextField()

    #: Date of creation, automatically set upon creation
    created_at = models.DateTimeField(auto_now=True)

    #: Type of class this is associated to
    owner_type = models.ForeignKey(ContentType)

    #: ID of the associated model
    owner_id = models.PositiveIntegerField()

    # Object to associate with
    content_object = GenericForeignKey('owner_type', 'owner_id')

    class Meta:
        ordering = ['-created_at']
```

I was about to implement this using the @factory.post_generation decorator but I wasn't quite sure how to associate the keys properly there either. Any more information on this?

**Comment by rbarrois** [comment]
At its core, factory_boy calls ``MyModel.objects.create(**kwargs)``, where ``**kwargs`` have been computed from the provided definitions.

For your model, the typical call would be:
``Comment(message="hello", content_object=some_object)``

Indeed, Django will compute the values of ``owner_type`` and ``owner_id`` from the passed-in object.

With factory_boy, if you want a factory building comments for a ``Post``, you could use:
```python
class PostCommentFactory(factory.django.DjangoModelFactory):
    message = factory.fuzzy.FuzzyText()
    content_object = factory.SubFactory(PostFactory)
```

**Comment by Amnesthesia** [comment]
Thank you rbarrois!

Would I have to make one of these factories for every Model that should be able to have a comment attached to it?

**Comment by rbarrois** [comment]
Well, that's up to you.

You can also use the following:

```python
class GenericCommentFactory(factory.django.DjangoModelFactory):
    message = factory.fuzzy.FuzzyText()
```

And then provide the target object in your tests: ``GenericCommentFactory(content_object=a_blog_post)``.

**Comment by rbarrois** [comment]
@Amnesthesia I'm closing the issue since it seem that the solution fixed your problem; feel free to reopen it if you need more help :)
