### ISSUE TITLE
faker.py does not install via pip - strange stuff!!

### ISSUE THREAD

**Issue by thebarty** [rbarrois/factory_boy#220]
Hi guys,

now this one is really strange. I just wanted to try the build-in faker and basically I am getting an attribute not found error:
```
>>> import factory
>>> factory.Faker('email')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Faker'
```

20 minutes later I had a look at the virtualenv/site-packages path and noticed that the file "faker.py" is missing. 

And after doing an...
```
pip uninstall factory-boy
pip install factory-boy
```
it is still missing!

Any ideas whats going wrong?

**Comment by adharris** [comment]
Looks to me like the Faker functionality is not on pypi yet. You can either wait for the next release or install from github.

**Comment by rajZenefits** [comment]
When is the release that includes faker scheduled?

**Comment by rbarrois** [comment]
@rajZenefits I'm hoping to get another feature (automatic factory declaration from model instrospection) in that release.
Hopefully, this should happen this week-end.

**Comment by skorokithakis** [comment]
Welp, I got hit by this exact same thing and came here to say what @MikeSmith12222 said, but apparently @rbarrois was too quick for me. Therefore, +1.

**Comment by skolsuper** [comment]
+1, *bump*

**Comment by aaronwhite** [comment]
+1, bump - live docs don't match latest release

**Comment by mmanderson** [comment]
+1, bump - just ran into this as well trying to follow the live docs examples

**Comment by talos** [comment]
+1 still an issue.

**Comment by rbwinslow** [comment]
+1, bump. Really complicates continuous integration when you have to automate this outside of requirements.txt.

**Comment by rbarrois** [comment]
Yep, sorry about that.

I need to fix my CI setup, I should be able to do a release next week.

**Comment by rbwinslow** [comment]
No worries, man. Thanks for the reply!

**Comment by Eagllus** [comment]
So this issue is from July 24, the latest documentation points out that `factory.Faker` can be used.
Currently this is still not the case, so any idea when this will be implemented?

**Comment by seddonym** [comment]
If you're looking for a workaround in the meantime, you can use faker directly instead:

    pip install fake-factory

Then you can do:

    import factory
    from faker import Factory as FakerFactory
    from ..models import MyModel

    faker = FakerFactory.create('en_GB')

    class MyModelFactory(factory.django.DjangoModelFactory):
        class Meta:
            model = MyModel

        first_name = factory.LazyAttribute(lambda obj: faker.first_name())
        last_name = factory.LazyAttribute(lambda obj: faker.last_name())
        phone = factory.LazyAttribute(lambda obj: faker.phone_number())
        email = factory.LazyAttribute(lambda obj: faker.email())

**Comment by rbarrois** [comment]
@Eagllus The implementation is here, but I haven't found the time to write proper docs yet.

I consider proper documentations a requirement to release a new feature, which explains why the release isn't available yet.

If all goes well, it should be up in a few hours, though.

**Comment by rbarrois** [comment]
Aaaand it's done :)

Sorry for the long delay :/
