### ISSUE TITLE
UserFactory example / performance tips

### ISSUE THREAD

**Issue by rpkilby** [rbarrois/factory_boy#224]
Hi, we're using factory_boy to generate test data during development and were running into unusual performance issues when it came to generating users. After some profiling, the culprit turned out to be a post generation hook on `set_password()`. To generate 1000 users, it was taking ~134 seconds. Since we don't care about unique passwords, generating the password once and reusing it dropped the time to 3 seconds.

Kind of obvious in retrospect (who knew password hashers were intentionally slow `¯\_(ツ)_/¯`), but figured it was worth mentioning in case someone else ran into a similar 'performance' issue. Not sure if it's worth adding a tip/warning to the documentation.

```python
from django.contrib.auth.hashers import make_password

class UserFactory(DjangoModelFactory):
    ...
    class Meta:
        model = models.User

    @factory.post_generation
    def password(self, create, extracted, **kwargs):
        if extracted is None:
            self.password = UserFactory.PASSWORD
        else:
            self.password = make_password(extracted)
UserFactory.PASSWORD = make_password('password')
```

Edit: updated password method to be correct

**Comment by rbarrois** [comment]
Hi,

Instead of changing this on the factory level, my solution is to alter the global hashers for the whole Django process when running tests:

```python
# settings.py
if ENVIRONMENT == 'test':
    PASSWORD_HASHERS = (
        'django.contrib.auth.hashers.UnsaltedMD5PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
        'django.contrib.auth.hashers.BCryptPasswordHasher',
        'django.contrib.auth.hashers.SHA1PasswordHasher',
        'django.contrib.auth.hashers.MD5PasswordHasher',
        'django.contrib.auth.hashers.CryptPasswordHasher',
    )
```

This has the advantage of accelerating login tests as well :)
Does this bring similar performance improvements?

**Comment by rpkilby** [comment]
Hi Raphael,

Good point - we have our password hashers configured this way for testing, but not for development. The performance cropped up because we were using the factories as a fake data generator, and the default PBKDF2 hasher ran every time.

I reran the tests and the performance was definitely comparable.
