### ISSUE TITLE
post equivalent for lazy_attribute

### ISSUE THREAD

**Issue by gilbsgilbs** [rbarrois/factory_boy#225]
Hi,
I would like to add abstration in my UserFactory(). I would like to give the user password as a parameter of my factory and let the factory generate the hashed password. For example, I would like to do something like this:
```python
user = UserFactory(password='foo')
print(user.password)  # prints a hash of the password foo
```
Even better, I would also like to be able to set the hash manuelle. Let's say doing something like this:
```python
user = UserFactory(__plain_password='bar')
print(user.password)  # prints a hash of the password bar
``` 

I've seen that we can pass parameters to `post_generation` functions using `MyFactory(post__a_var=3)` and `kwargs['a_var']`. Technically, it would be possible to patch the password in a post_generation function, but I find this a bit dirty. On the other hand, I don't think that we can really use a similar solution for LazyAttributes as I would like to.

If it's currently not possible, do you think that I could contribute to the project in this direction, or that it would go against factory_boy's spirit?

Thank you!
Gilb's

**Comment by rbarrois** [comment]
Hi,

I think this feature is described in the ``PostGenerationMethodCall`` docs: http://factoryboy.readthedocs.org/en/latest/reference.html#postgenerationmethodcall

Does that match your use case?

**Comment by fayazkhan** [comment]
I had a case where I needed the attribute to be generated before constructor was called, but after the other parameters were processed. (Maybe there might have been a BetterWayToDoIt)

**Comment by jeffwidman** [comment]
Closing for now, as @gilbsgilbs never replied back. `PostGenerationMethodCall` should work for vast majority of use cases. That said, if there's a clearly described scenario where it doesn't work, we'd definitely be open to a PR adding functionality here. I think it's unlikely that the core team will implement it, as there's a number of other features that would be more useful for average user, such as #251.

**Comment by jcquarto** [comment]
an area where I'm unsure how `PostGenerationMethodCall` should work is when something other than a literal string is passed in. 

for example,  `u = UserFactory(username='fred')`, where for the sake of discussion, I want to set the password to 'fred', matching the username on a instance by instance basis.  I''d've thought this would come from soemthing like this in the Factory definition:  
```
class UserFactory(factory.django.DjangoModelFactory):
password = factory.PostGenerationMethodCall('set_password', self.username)
```

which doesn't quite work.  And what if we have soemthing dynamic in the Factory definition of `username`? Such as:

```
class UserFactory(factory.django.DjangoModelFactory):
username = factory.Sequence(lambda n: 'admin{0}'.format(n)). #or, similarly, using faker.name()
```
so now the password is a Lazy Attribute?  or...?
