### ISSUE TITLE
Does SubFactory related object creation still work in Django 1.8? 

### ISSUE THREAD

**Issue by cnk** [rbarrois/factory_boy#234]
The docs show creating an object and a related object in a single call: 
https://factoryboy.readthedocs.org/en/latest/index.html#associations
```python
# Builds and saves a User and a Post
>>> post = PostFactory()
>>> post.id is None  # Post has been 'saved'
False
>>> post.author.id is None  # post.author has been saved
False
```

Does this still work in Django 1.8? I know that it won't work if you use .build() but I can't seem to get it to work with create either. 

https://gist.github.com/anonymous/92e936dfe7a1b1310b84

**Comment by rbarrois** [comment]
This still works; the issue in your test if that when you call ``MultipleChoiceAnswerFactory.build()``, the underlying behavior is:

```python
# MultipleChoiceAnswerFactory.build()
question = MultipleChoiceQuestion(
    title="First MultipleChoiceQuestion",
    question_text="What is 2 + 2?",
    correct_answer=None,
)

answer = MultipleChoiceQuestionAnswer(
    question=question,
    sync_attribute="answer_1",
    answer_text="4",
)
# End of the factory

answer.full_clean()
```

Here, ``answer.full_clean()`` sees that ``answer.question_id is None``, and breaks accordingly.
See the note in http://factoryboy.readthedocs.org/en/latest/orms.html#the-djangomodelfactory-subclass for details.
