### ISSUE TITLE
ordered post_generation functions

### ISSUE THREAD

**Issue by zdelagrange** [rbarrois/factory_boy#240]
Order of post_generation function calls does not seem obvious. currently it seems that post_generation functions are run in a sorted order based on function name. I would like to be able to run my post_generation functions in a specific order without having to confuse the function name.

**Comment by rbarrois** [comment]
This could be implemented; do you have an idea of the API you'd like to see?

**Comment by zdelagrange** [comment]
What about an int argument to the post_generation decorator? so I could decorate my functions like

@post_generation(1)
@post_generation(2)

This was inspired by locus.io's use of their weighted tasks. http://docs.locust.io/en/latest/api.html?highlight=task#locust.core.task

**Comment by olegpidsadnyi** [comment]
I'm suffering from this a lot. How about I implement it?
There's absolutely no need in passing an integer parameter. Let's do it like Django does in the forms.
All we need is to preserve the order of the declaration.
So all instantiations of the declaration can simply increment one global creation counter and store the value on the declaration instance. This way they can be sorted when needed.
