### ISSUE TITLE
Faker.generate should allow calling without any kwargs

### ISSUE THREAD

**Issue by mapleoin** [rbarrois/factory_boy#246]
`Faker.generate` currently requires kwargs, but doesn't need them i.e. `Flaker(...).generate({})` will work just fine with most providers. The kwargs attribute should be optional. It would also be good if the kwargs were really kwargs, not just a passed-in dict.

**Comment by rbarrois** [comment]
Hi,

Would an update that adds support for ``Faker(...).generate()`` fix this for you?

I've been bitten too many times with using ``**kwargs`` to pass a dict parameter, as that prevents adding any further parameters to the function without breaking compatibility.
However, the ``extra_kwargs`` parameter could easily be rendered optional.

**Comment by rbarrois** [comment]
Actually, this is an internal API; do you have an example of code where this limitation hurts?

**Comment by mapleoin** [comment]
I'm trying to remember why I opened this. It now looks to me like I didn't understand how the Faker class worked. My example from the test: `Faker('random_int').generate(min=1, max=100)` can be rewritten as `Faker('random_int', min=1, max=100)` which I suppose is the recommended API.

> I've been bitten too many times with using **kwargs to pass a dict parameter, as that prevents adding any further parameters to the function without breaking compatibility.

Does it? You can just add them before. The risk of name clashing shouldn't be that great.

> Actually, this is an internal API; 

Should `Faker.generate` be `Faker._generate` then?

I'll just leave this open in case you want to decide to make those methods more *private* so others don't stumble like I did. The original issue I reported is invalid.

**Comment by rbarrois** [comment]
Thanks for the input :)

I should maybe make it clearer which unittests are using internal APIs and which are testing public attributes then!
