### ISSUE TITLE
How is this different than factory_girl? 

### ISSUE THREAD

**Issue by jfeldstein** [rbarrois/factory_boy#250]
First thing on my mind is "how are they different?"

Strange that this topic is not covered in the docs... A blurb in the README covering "Why use vs factory_girl" would be very helpful for future discoverers.

I am a long-time factory_girl user, who only just recently discovered factory_boy. It's obvious you've done... something(s) different, but I would very much appreciate a concise summary. 

Thanks!

**Comment by benregn** [comment]
I think that maybe the next biggest difference between the two is the fact that factory_girl is written in Ruby, and factory_boy is written in Python. :smile:

I haven't used factory_girl so I cannot tell you the difference in features.

**Comment by rbarrois** [comment]
Indeed ;)

factory_boy started as a Python port of factory_girl — but their paths have likely diverged since then
