### ISSUE TITLE
FileField - filename doesn't overwrite when from_path

### ISSUE THREAD

**Issue by darkowic** [rbarrois/factory_boy#257]
I have factory similar to this:

```python
class TestFactory(factory.django.DjangoModelFactory):
    class Meta:
        model=Test
     
    file_field = factory.django.FileField(filename='default.png')
```
I tried to use it like in this example:

```python
path_to_file = 'some/path/to/file.txt'

xxx = TestFactory(file_field__from_path=path_to_file)
print(xxx.file_field.name)
```
The result is `default.png` and file isn't save. From documentation:

>from_path (str) – Use data from the file located at from_path, and keep its filename

So in my opinion result should be `file.txt`. Am I right? I'm little confused about it :)

**Comment by rbarrois** [comment]
Well, that's a good question.

From the factory's point of view, it only gets the equivalent of ``file_field = factory.django.FileField(filename='default.png', from_path='some/path/to/file.txt')``.

In that context, it has no way to decide which filename the user wants to use; the current rule is that ``filename`` takes precedence.

I'll update the docs accordingly, thanks for noting this!
