### ISSUE TITLE
Docs shouldn't endorse writing randomized tests

### ISSUE THREAD

**Issue by aaugustin** [rbarrois/factory_boy#259]
From https://factoryboy.readthedocs.org/en/latest/:

> Tests look better with random yet realistic values.

Some people, myself included, believe it's a good practice to use fixed values in tests in order to avoid random failures. Even if you think it's a good idea to use random data in tests, I think it would be honest to acknowledge the drawback in that paragraph.

**Comment by rbarrois** [comment]
Indeed, updated.

Also, now that faker allows to set/reset its random seed easily, reproducible "random" tests should be easier to setup (see https://github.com/joke2k/faker/issues/317).

**Comment by aaugustin** [comment]
That's much better, thanks!
