### ISSUE TITLE
RelatedFactory lazy arguments from parent

### ISSUE THREAD

**Issue by bryanph** [rbarrois/factory_boy#264]
The dot-notation which is in the docs w.r.t Subfactories for getting a parent attribute, does not work for RelatedFactory.

For example:

```python
class SearchFactory(ActivityFactory):
    """A complete search field factory for testing search"""
    
    class Meta:
        model = models.Activity
        exclude = ('title_1', 'title_2', 'description_1', 'description_2',)

    # narrative contents, override these when required
    title_1 = "title narrative1"
    title_2 = "title narrative2"
    description_1 = "description narrative1"
    description_2 = "description narrative2"

    title = RelatedFactory(TitleSearchFactory, 'activity', 
            content_1=factory.SelfAttribute('..title_1'), 
            content_2=factory.SelfAttribute('..title_2'))
```

This will result in an error:
    target = containers[self.depth - 2]
    IndexError: tuple index out of range

I was wondering whether this was desired behaviour or a bug? I am looking for a way to pass arguments to the RelatedFactory.

**Comment by rbarrois** [comment]
Well, that's a "doc bug".

The behavior you wish can be obtained by calling:

```python
class SearchFactory(ActivityFactory):
    """A complete search field factory for testing search"""

    class Meta:
        model = models.Activity
        exclude = ('title_1', 'title_2', 'description_1', 'description_2',)

    # narrative contents, override these when required
    title_1 = "title narrative1"
    title_2 = "title narrative2"
    description_1 = "description narrative1"
    description_2 = "description narrative2"

    title = RelatedFactory(TitleSearchFactory, 'activity', 
            content_1=factory.SelfAttribute('activity.title_1'), 
            content_2=factory.SelfAttribute('activity.title_2'))
```

Behind the scenes, the actual behavior when calling ``SearchFactory()`` will be:
1) ``activity = SearchFactory(title=None)``
2) ``title = TitleSearchFactory(activity=activity, content_1=factory.SelfAttribute('activity.title_1'))``
3) ``return activity``

So, the parameters to ``TitleSearchFactory`` are evaluated in a scope where the ``SearchFactory`` has already been cleaned.

**Comment by Storyyeller** [comment]
I just ran into this issue as well. It would be nice if this could be explained in the documentation somewhere.
