### ISSUE TITLE
Switch from Makefile to Tox

### ISSUE THREAD

**Issue by jeffwidman** [rbarrois/factory_boy#273]
Be nice to replace the complicated Makefile with a much simpler `tox` setup:

1. Tox would make it easy to setup a build matrix of different python versions + various sqlalchemy/django versions. 
2. Tox runs each build within a dedicated virtualenv, no need for the setup/teardown routines in the makefile.

Here's an example setup from one of my projects: https://github.com/jeffwidman/flask-uploads/blob/master/tox.ini
It plays well with Travis: https://github.com/jeffwidman/flask-uploads/blob/master/.travis.yml
Resulting in this build matrix: https://travis-ci.org/jeffwidman/flask-uploads

@rbarrois any reason that using tox might not be possible? I don't work with makefiles very often, and not sure if there's specific functionality that I missed that requires a makefile instead of tox.

**Comment by rbarrois** [comment]
@jeffwidman the main reason is that I've never used tox myself :)

I have no strong opinions on the testing toolchain, as long as it supports:
- Easily running the tests within an active virtualenv (i.e a single command runs everything)
- Easy to disable tests for parts of the system (i.e "I don't run a mongodb server, don't run those tests")

The main advantage of the Makefile is that it documents typical commands (building docs, running tests, …) ; but I don't mind changing those commands.

**Comment by jeffwidman** [comment]
basically the point of tox is to handle the setup/teardown of a virtualenv with the required dependencies. 

the actual commands to build docs/run tests are still part of a tox config. I can try taking a stab at this.

**Comment by rbarrois** [comment]
@jeffwidman I've had a look at tox for a few projects and, indeed, it's pretty nice.

I'll have a look at this soon; I'm likely to keep the Makefile for common tasks, but handling the matrix in tox would be much simpler :)

**Comment by jeffwidman** [comment]
Yeah, I did take a look at this for a bit, and had the opposite of your confusion of `tox`, I got confused by some of the `Makefile` syntax :-). I had it in my list of things to read up on, and just never got to it.
