### ISSUE TITLE
factory_boy should be able to figure out that a model is abstract by itself

### ISSUE THREAD

**Issue by aaugustin** [rbarrois/factory_boy#280]
The docs give this example:

```python
class MyAbstractModelFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = models.MyAbstractModel
        abstract = True

class MyConcreteModelFactory(MyAbstractModelFactory):
    class Meta:
        model = models.MyConcreteModel
```

It seems to me that `Meta.abstract` could and should default to `Meta.model._meta.abstract`.

**Comment by rbarrois** [comment]
@aaugustin Well, this was an obsolete piece of docs.

I've just added a test that confirms that setting the ``abstract=True`` flag is not required.
