### ISSUE TITLE
LazyFunction missing in pypi

### ISSUE THREAD

**Issue by jab3z** [rbarrois/factory_boy#282]
Hello,

LazyFunction import from .declarations is missing from pypi version even if it seems to be the same with the latest master version, 2.6.1.

Dacian

**Comment by jeffwidman** [comment]
LazyFunction was the first new commit after the 2.6.1 release. The 2.6.2 release will include this.

**Comment by Gaffney** [comment]
Stumbled on this too. I believe this is underlying source of confusion:

<img width="590" alt="confusing" src="https://cloud.githubusercontent.com/assets/1113620/14546816/cd4c8c2c-025c-11e6-9e8f-ab297166d40a.png">

**Comment by jeffwidman** [comment]
@ericholscher see above--`2.6.1` is the latest PyPI release, yet the link points to latest. Is showing the latest PyPI release for the dev version the RTD default or did we click a wrong button somewhere?

**Comment by jeffwidman** [comment]
I filed a bug on RTD about the docs issue. 

2.7 is now live on Pypi, fixing the missing `LazyFunction` part: f1ed74e06dfb6851bc691ebfd8135c875154ad50
