### ISSUE TITLE
Releasing 2.7: are we ready?

### ISSUE THREAD

**Issue by rbarrois** [rbarrois/factory_boy#288]
I'm thinking of releasing 2.7 soon (by the end of the week, basically).
This includes:
- ``LazyFunction``
- ``Traits``
- Remove Python2.6 support (fitting with the release version :P)

@jeffwidman do you think you're ready? Or do you think we need more docs on one of those topics?

**Comment by jeffwidman** [comment]
Sorry for the delay here. I have no objections, let's pull the trigger.

**Comment by rbarrois** [comment]
Awesome, I'll handle the release tomorrow (too busy last week :/)

**Comment by rbarrois** [comment]
Released as f1ed74e06dfb6851bc691ebfd8135c875154ad50 \o/
