### ISSUE TITLE
TypeError: when factory class has a post_generation function with the name 'attributes'

### ISSUE THREAD

**Issue by Divoo** [rbarrois/factory_boy#291]
I have `Product` model that has a `ManyToManyField` to `Attribute` model:
```
class Product(models.Model):
    company = models.ForeignKey("companies.Company")
    subcategory = models.ForeignKey("categories.SubCategory")
    name = models.CharField(_("Name"), max_length=120)
    attributes = models.ManyToManyField(Attribute)
```

It's corresponding factory class `ProductFactory`:
```
class ProductFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = "products.Product"

    company = factory.SubFactory(CompanyFactory)
    subcategory = factory.SubFactory(SubCategoryFactory)
    name = factory.sequence(lambda n: 'Product-{0}'.format(n))

    @factory.post_generation
    def attributes(self, create, extracted, **kwargs):
        if not create:
            # Simple build. do nothing.
            return

        if extracted:
            # A list of attributes were passed in.
            for attribute in extracted:
                self.attributes.add(attribute)
``` 

Now when I create a new object using the `ProductFactory`
```
>>> p = ProductFactory()
```

An exception raised
```
TypeError                                 Traceback (most recent call last)
factory/base.py in create(cls, **kwargs)
def create(cls, **kwargs):
---> attrs = cls.attributes(create=True, extra=kwargs)
       return cls._generate(True, attrs)

TypeError: 'PostGeneration' object is not callable
```

As a **workaround** to this problem I changed the name of the field `attributes` to `product_attributes`.

Is there any solution to keep my field name `attributes` as it's without changing it.

**Comment by rbarrois** [comment]
Well, the name of post-generation declarations on a factory need not be the same as the reverse related field thay map to.

So, you could call that post-generation declaration ``product_attributes`` or ``attributes_`` without problem (on the factory, no need to change the actual model).

``attributes`` is one of the expected class methods, along with ``build``, ``create`` and a few other ones.

Is that a huge issue for your code, or is the workaround good enough for now?

**Comment by Divoo** [comment]
Thanks @rbarrois this workaround is great for me.

And just as a reference for anyone having the same problem with field names, check [`rename`](https://factoryboy.readthedocs.org/en/latest/reference.html#factory.FactoryOptions.rename).

**Comment by rbarrois** [comment]
Great, thanks! I'm closing the issue now :)
