### ISSUE TITLE
Unable to access factory_parent in RelatedFactory LazyAttribute.

### ISSUE THREAD

**Issue by schinckel** [rbarrois/factory_boy#296]
In https://factoryboy.readthedocs.org/en/latest/recipes.html#copying-fields-to-a-subfactory, it's shown that it's possible to copy fields from the parent factory, using as `LazyAttribute` that access `factory_parent`.

However, this is not set on a `RelatedFactory`, making it impossible to access a value that exists on the factory, but not on the object.

I was hoping to use one field to populate several derived objects, but these require using a `RelatedFactory`, as they have a foreign key to the object that is in the parent factory.

**Comment by schinckel** [comment]
I assume this is because the parent factory has not evaluated/executed yet. I wonder if there is a workaround.

**Comment by rbarrois** [comment]
Hi!

What happens when ``FooFactory`` has a ``RelatedFactory`` on ``BarFactory`` is:
1. Create a ``Foo`` instance with ``FooFactory``
2. Pass that concrete instance as an argument to ``BarFactory``

So, it might indeed be somewhat complicated to setup as you'd expect :/

If you have some concrete code, I could try to look at options :)

**Comment by schinckel** [comment]
Part of my problem is that I've been trying to do it in a large project, where running tests takes around 12mins, so it's a slow turnaround.

I've come up with a solution in a simplified environment, but I'm not sure I've captured all of the stuff from the original project that was pertinent. I'll surely be back here soon!

**Comment by schinckel** [comment]
Thanks for the prompt reply, by the way.

**Comment by schinckel** [comment]
Okay, I think I have a reasonable suggestion of the problem.

The issue only really occurs because I need the default for a value that is used by two related factories to be the same, unless either or both of them are explicitly overridden. In the example below, the `employment.start` (which actually populates the lower part of a `DateRange`, but that's irrelevant), should match the `primary_location.effective_from`, unless they are explicitly provided.

    class EmployeeFactory(factory.django.DjangoModelFactory):
        class Meta:
            model = 'employee.Employee'

        name = factory.Faker('name')
        date_of_birth = factory.Faker('date')

        employment = factory.RelatedFactory('employee.factories.EmploymentFactory',
                                            'employee',
                                            start=factory.Faker('date'))
        primary_location = factory.RelatedFactory('employee.factories.PrimaryLocationFactory',
                                                  'employee',
                                                  effective_from=factory.Faker('date'))


    class EmploymentFactory(factory.django.DjangoModelFactory):
        class Meta:
            model = 'employee.Employment'
            exclude = ('start', 'finish')

        employee = factory.SubFactory('employee.factories.EmployeeFactory',
                                      employment=None)
        period = factory.LazyAttribute(lambda o: (o.start, o.finish))
        termination_reason = None

        start = factory.Faker('date')
        finish = None


    class LocationFactory(factory.django.DjangoModelFactory):
        class Meta:
            model = 'employee.Location'

        name = factory.Faker('company')


    class PrimaryLocationFactory(factory.django.DjangoModelFactory):
        class Meta:
            model = 'employee.PrimaryLocation'

        employee = factory.SubFactory(EmployeeFactory, primary_location=None)
        location = factory.SubFactory(LocationFactory)
        effective_from = factory.LazyFunction(datetime.date.today)

Does this make sense? Can you think of a solution?

**Comment by schinckel** [comment]
Oh, it's worth noting that the field in question does not appear anywhere on the `Employee` model, so we don't get access to it within a `factory.SelfAttribute()` construct.

**Comment by rbarrois** [comment]
@schinckel You could use:
- A ``Params`` section for your ``start_date``
- Define ``employment__start=factory.SelfAttribute('start_date')`` in ``EmployeeFactory``

=> This will resolve ``employment__start`` in the context of ``EmployeeFactory`` (where ``start_date`` is available) and pass the computed value as ``start=...`` to your ``EmploymentFactory``

I have added a test to show how this could work; your ``EmployeeFactory`` would then look like this:

```python

class EmployeeFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = 'employee.Employee'

    class Params:
        start_date = factory.Faker('date')

    name = factory.Faker('name')
    date_of_birth = factory.Faker('date')

    employment = factory.RelatedFactory('employee.factories.EmploymentFactory',
                                        'employee')
    employment__start_date = factory.SelfAttribute('start_date')

    primary_location = factory.RelatedFactory('employee.factories.PrimaryLocationFactory',
                                              'employee')
    primary_location__start_date = factory.SelfAttribute('start_date')
```

**Comment by rbarrois** [comment]
@schinckel This should answer your question, hopefully :)

I'm closing the issue, feel free to reopen it if that doesn't work ;)
