### ISSUE TITLE
Add test case for missing key in django_get_or_create

### ISSUE THREAD

**Issue by rrauenza** [rbarrois/factory_boy#297]

**Comment by rrauenza** [comment]
So looking at this, the test case is fairly easy to add, but I'm not sure the best approach for the DRY-ness.

You already have

```
class StandardFactoryWithPKField(factory.django.DjangoModelFactory):        
        class Meta:                                                             
            model = models.StandardModel                                        
            django_get_or_create = ('pk',)                                      
                                                                                
        foo = factory.Sequence(lambda n: "foo%d" % n)                           
        pk = None   
```

And then

```
 def test_missing_pk(self):                                                  
                                                                                
        std = StandardFactoryWithPKField()                                      
        self.assertIsNotNone(std.pk)                                            
        self.assertEqual('foo0', std.foo)   
```

The reason this doesn't trigger the exception is because pk is already given a default value of None in the factory class.

If I remove ```pk = None``` from the factory class, the exception is properly triggered.

It's also a little weird having ```pk``` be the key in the django_get_or_create class.

Maybe I'll just make a new class ...?

**Comment by rbarrois** [comment]
@rrauenza Indeed, the code was unclear; actually, we didn't have proper tests for this behavior.
I've just fixed that ;)
