### ISSUE TITLE
Simplifying how to use Faker wrapper within Factories

### ISSUE THREAD

**Issue by jsangilve** [rbarrois/factory_boy#301]
While creating a Factory with a Django's `ImageField`, I realized that I needed different `filename` values for each `ImageField`. So, I tried this:

```python
import factory
import faker import Factory as FakerFactory

def gen_filename():
    return FakerFactory.create().file_name()

class BannerFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = models.Banner

    image = ImageField(filename=factory.LazyFunction(gen_filename))

    ... other fields
```
Then, I thought it'd be simpler to use factory_boy's faker wrapper instead of going directly with Faker,  so I changed gen_file function to:
```python
def gen_filename():
    return factory.Faker('file_name').generate({})
```

So, unless I'm missing something,  `extra_kwargs` parameter in Faker's generate method could become optional. As a result, you would be able to call `factory.Fake('provider').generate()` without the empty/unintuitive dict.

I already made this change in my fork https://github.com/jsangilve/factory_boy/commit/4f6be9e4b6c1b39e3433c816e4e8fc6602dc8b55.

**Comment by rbarrois** [comment]
Have you tried calling ``image=ImageField(filename=factory.Faker('file_name'))``?

The proper usage of ``factory.Faker`` is described at http://factoryboy.readthedocs.io/en/latest/reference.html#faker ; the ``.generate()`` function is an implementation detail and not an official API.

**Comment by jsangilve** [comment]
thanks for your reply @rbarrois. I did try that but it didn't work. I must have been doing something else wrong.
