### ISSUE TITLE
Cannot use list comprehension inside FuzzyChoice field with Django

### ISSUE THREAD

**Issue by alexandre-figura** [rbarrois/factory_boy#313]
I recently went into an issue while using a list comprehension inside a ``FuzzyChoice`` field with a ``DjangoModelFactory``, using **factory_boy 2.7.0** and **Python 2.7.11**. For example:

```
FIELD_CHOICES = (
    (0, 'zero'),
    (1, 'one'),
)

class MyModel(django.db.models.Model):
    some_field = django.db.models.IntegerField(choices=FIELD_CHOICES)

class MyFactory(factory.django.DjangoModelFactory):
    some_field = factory.fuzzy.FuzzyChoice([choice[0] for choice in FIELD_CHOICES])

    class Meta:
        model = MyModel
```

This generates the following error while creating an instance of the factory:

```
Traceback (most recent call last):
  File "/my_project/my_django_project/my_django_app/tests.py", line 14, in some_test
    MyFactory()
  File "/my_project/eggs/factory_boy-2.7.0-py2.7.egg/factory/base.py", line 67, in __call__
    return cls.create(**kwargs)
  File "/my_project/eggs/factory_boy-2.7.0-py2.7.egg/factory/base.py", line 595, in create
    return cls._generate(True, attrs)
  File "/my_project/eggs/factory_boy-2.7.0-py2.7.egg/factory/base.py", line 520, in _generate
    obj = cls._prepare(create, **attrs)
  File "/my_project/eggs/factory_boy-2.7.0-py2.7.egg/factory/base.py", line 495, in _prepare
    return cls._create(model_class, *args, **kwargs)
  File "/my_project/eggs/factory_boy-2.7.0-py2.7.egg/factory/django.py", line 181, in _create
    return manager.create(*args, **kwargs)
  File "/my_project/eggs/Django-1.6.5-py2.7.egg/django/db/models/manager.py", line 157, in create
    return self.get_queryset().create(**kwargs)
  File "/my_project/eggs/Django-1.6.5-py2.7.egg/django/db/models/query.py", line 320, in create
    obj = self.model(**kwargs)
  File "/my_project/eggs/Django-1.6.5-py2.7.egg/django/db/models/base.py", line 417, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'choice' is an invalid keyword argument for this function
```

It appears that the variable ``choice``, which is used inside the list comprehension, is also used to initialize the Django model ( which does not have such field).

Apparently, this variable is added [here](https://github.com/rbarrois/factory_boy/blob/master/factory/base.py#L218), while executing the method ``factory.base.FactoryOptions.contribute_to_class``.

When I replace the list comprehension by a generator expression, everything is fine.

I do not know if we can modify the method ``factory.base.FactoryOptions._is_declaration`` to avoid this behavior. Otherwise, maybe put a note about this in the documentation?

**Comment by alexandre-figura** [comment]
Moreover, this problem does not happen in Python 3, as list comprehensions have their own scope in this version. The loop control variable "leaks" into the surround scope only in Python 2.

**Comment by jeffwidman** [comment]
This is a great bug report, thanks for testing with both Python2/3. 

I'm not super familiar with Django, but in general the `Fuzzy` attributes are deprecated: http://factoryboy.readthedocs.io/en/latest/fuzzy.html#module-factory.fuzzy

I'm going to close this, as I assume one of the alternatives available through the `Faker` library will do what you want. If not, leave a comment explaining why and we can re-open.

**Comment by rbarrois** [comment]
@alexandre-figura this is indeed a scope-bleeding bug, as documented [in the tests](https://github.com/rbarrois/factory_boy/blob/master/tests/test_using.py#L1609,L1635) and first discovered in #6.

In your case, you can fix it by naming your loop variable ``_choice``, as shown in the test above.

This will affect all declarations using a list comprehension under Py2, not just Fuzzy ones.

Unfortunately, factory_boy has no easy way to detect such scope bleeding: the call to ``__new__(mcs, name, bases, attrs)`` from Python's type system will pass in the same list of attrs in the following two classes:

```python
class Foo(object):
    x = [y ** 2 for y in range(4)]

# Equivalent to:
Foo = type.__new__('Foo', [], {'x': [0, 1, 4, 9], 'y': 3})

class Bar(object):
    x = [y ** 2 for y in range(4)]
    y = 3

# Equivalent to:
Bar = type.__new__('Bar', [], {'x': [0, 1, 4, 9], 'y': 3})
```
