### ISSUE TITLE
DjangoModelFactory doesn't support raw loading

### ISSUE THREAD

**Issue by DXist** [rbarrois/factory_boy#67]
factory_boy can be used to replace django fixtures.  

Fixtures
* create model instances using instance.save_base(raw=True, **kwargs). raw=True is passed to post_save handlers
* load data for parent and child model separately in case of multi-table inheritance (MTI)

DjangoModelFactory
* creates models instances using models manager's create method. post_save handlers are invoked with raw=False
* calls child save method in case of MTI, no need to save parent model separately

Issue objective
* support raw kwarg for DjangoModelFactory.create: MyModelDjangoFactory.create(raw=True, **kwargs). When raw is True create method calls save_base instance method
* handle MTI case and call save_base for all models from hierarchy for given model

**Comment by jeffwidman** [comment]
@DXist any update here?

**Comment by DXist** [comment]
@jeffwidman , I'm afraid I haven't used Factory Boy for a long time. @rbarrois , sorry for not providing any reply. I've shared all custom code that I had more than 2 years ago.

**Comment by jeffwidman** [comment]
No worries, thanks for getting back to me. I'm going to close this for now, if anyone else is interested in this behavior we can certainly re-open for discussion.
