### ISSUE TITLE
Loading and dumping to and from data

### ISSUE THREAD

**Issue by mehcode** [rbarrois/factory_boy#73]
What does everyone think about adding a load/dump API that takes/consumes lists of dictionaries? This would allow for easy consuming and producing JSON / YAML fixtures.

Something like the following.

```python

import factory
from . import models

class UserFactory(factory.Factory):
    FACTORY_FOR = models.User

    first_name = 'John'
    last_name = 'Doe'
    admin = False

# Deserialize an iterable of dictionaries using the factory.
UserFactory.load([{...}, {...}])

# Serialize an iterable of targets to an list of dictionaries
# factoring out attributes provided by factories, etc. 
data = UserFactory.dump([models.User(first_name="Bob"), 
                         models.User()])

assert 'first_name' not in data[1]
```

**Comment by jeffwidman** [comment]
@mehcode Can you explain a little more about the scenarios you'd find the `load` behavior useful? 

I've never personally run into a situation where this was necessary... if I want to specify what appears in the DB, then I can just submit it straight to the ORM. If I need to pull from a list of specific options when creating a Factory, then I pass the list of option to the Factory. 

That said, the `dump` behavior would be convenient for using fake data created by FactoryBoy in API testing (see https://github.com/rbarrois/factory_boy/issues/68#issuecomment-181269862).

**Comment by jeffwidman** [comment]
Closing for now due to lack of interest. If someone stumbles across this and really wants this, feel free to leave a comment and we can re-open.
