### ISSUE TITLE
Add ability to freeze objects

### ISSUE THREAD

**Issue by thedrow** [rbarrois/factory_boy#95]
This code works for me however there are no tests or documentation so I am not going to create a pull request yet if at all (it depends on how much time I have).

```python
class FreezeableFactory(factory.Factory):
    _freezed = None
    _should_freeze = False

    @classmethod
    def freeze(cls):
        cls._should_freeze = True

    @classmethod
    def unfreeze(cls):
        cls._should_freeze = False
        cls._freezed = None

    @classmethod
    def _build(cls, target_class, *args, **kwargs):
        if not cls._should_freeze:
            return target_class(*args, **kwargs)
        if not cls._freezed:
            cls._freezed = target_class(*args, **kwargs)

        return cls._freezed

    @classmethod
    def _create(cls, target_class, *args, **kwargs):
        if not cls._should_freeze:
            return target_class(*args, **kwargs)
        if not cls._freezed:
            cls._freezed = target_class(*args, **kwargs)

        return cls._freezed
```

This allows you to ensure sub factories will return the same object. It is useful in situations where you need to create multiple objects with the same foreign key.
AutoFixture which is the same as factory_boy but for C# has exactly this useful feature.

**Comment by rbarrois** [comment]
Hi,

I'm unsure about this feature; I'd rather use ``django_get_or_create`` and friends instead.

Another option would be to have ``freeze`` be a context manger:
```python
with MyFactory.freeze():
    SomeDependantFactory.create_batch(size=40)
```

However, this can easily be handled through ``SomeDependantFactory.create_batch(40, parent=MyObject)``.

**Comment by jeffwidman** [comment]
I've been very happy just using `parent=MyObject` in my projects and personally don't see the need to add explicit freezing.
